### ISSUE TITLE
rabbitmq no more index entries in atom_tab(max=1048576)

### ISSUE THREAD

**Issue by huangyonghome** [rabbitmq/discussions#100]
HI
we often encounter below problem on several Rabbitmq cluster nodes since we have installed a python monitor script which get data through Rabbitmq web management periodically.

```
Oct  7 04:11:25 mq-es-node3 rabbitmq-server[2274]: Crash dump is being written to: erl_crash.dump...done  
Oct  7 04:11:25 mq-es-node3 rabbitmq-server[2274]: no more index entries in atom_tab (max=1048576)  
Oct  7 04:11:25 mq-es-node3 systemd[1]: rabbitmq-server.service: Main process exited, code=exited, status=1/FAILURE  
Oct  7 04:11:26 mq-es-node3 rabbitmqctl[2511]: Stopping and halting node 'rabbit@mq-es-node3' ...  
Oct  7 04:11:26 mq-es-node3 rabbitmqctl[2511]: Error: unable to connect to node 'rabbit@mq-es-node3': nodedown  
```
![image](https://user-images.githubusercontent.com/40015415/80697476-93df2f80-8b0b-11ea-9050-f49520ffb5d2.png)

I googled this problem and searched the similar error here.I heard that this issue was resolved since rabbitmq v3.6.5 . 

So I upgrade the rabbitmq version from v3.6.2 to v3.6.5 on our production environment. But I still experienced the same problem.

There is another strange question troubled us . Once the error causes the restart of Rabbitmq progress .The rabbitmq_delayed_message_exchange  plugin couldn't  work anymore, all message data which storage in delay queue would be lost. At the end, we have to replace a server.

`rabbitmq version: 3.6.5
erl version: 18.3`

Could you please help me to check on this ? Thank you in advance

**Comment by michaelklishin** [comment]
I cannot suggest what may be happening with the delayed message exchange plugin without server logs or steps to reproduce. The plugin has a [fair number of limitations](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#limitations). One of them is that if the plugin is disabled, all of the internal tables it uses will be deleted. Delayed messages reside on a single cluster node and while they are stored on disk as well as in RAM, this only provides so much in terms of availability.

We won't be investigating issues with RabbitMQ 3.6 since it's been out of support for 2 years. Please upgrade to `3.8.3`.
