### ISSUE TITLE
topic permission regexp has slashes not working

### ISSUE THREAD

**Issue by pigwing** [rabbitmq/discussions#110]
Write regexp: 1000/.* Read regexp: 1000/.*
when i subscribe or publish     1000/abc    no authority

**Comment by michaelklishin** [comment]
I'm afraid I cannot reproduce.

Given the following dedicated user and permissions:

``` shell
rabbitmqctl add_user "guest2" "guest2"
# => Adding user "guest2" ...
rabbitmqctl set_permissions -p "/" "guest2" ".*" ".*" ".*"
# => Setting permissions for user "guest2" in vhost "/" ...
rabbitmqctl set_topic_permissions -p "/" "guest2" "amq.topic" "1000/.*" "1000/.*"
# => Setting topic permissions on "amq.topic" for user "guest2" in vhost "/" ...
```

I connect as that user from a Ruby REPL and publish several messages: first with the routing key = "1000/abc", then two with the routing key = "2000/abc".

The first batch is published without any issues or errors logged. The second one results in a channel exception due to a permission violation:

```
2020-06-08 09:28:14.677 [error] <0.777.0> Channel error on connection <0.768.0> (127.0.0.1:50899 -> 127.0.0.1:5672, vhost: '/', user: 'guest2'), channel 1:
operation basic.publish caused a channel exception access_refused: access to topic '2000/abc' in exchange 'amq.topic' in vhost '/' refused for user 'guest2'
```

So permissions are enforced as I'd expect them to be.

Perhaps check if the permissions are for the correct virtual host or exchange, or that the pattern is not altered by the shell.
