### ISSUE TITLE
How to use CommandLineRunner within SpringBoot?

### ISSUE THREAD

**Issue by lhm0924** [rabbitmq/discussions#114]
I created a SpringBoot project like the tutorial demo,but when i run it with "receiver" as profiles option? it doesn't work.The receiver cannot consume messages.
------------------------------------------------------------------
 __                 __   ___                  
|__)_ |_ |_ .|_|\/|/  \   |    |_ _  _. _ | _ 
| \(_||_)|_)||_|  |\_\/   | |_||_(_)| |(_||_) 
                                              
2020-06-16 15:16:58.671  INFO 2348 --- [           main] com.example.demo.DemoApplication         : Starting DemoApplication on lhm-lenovo with PID 2348 (D:\prj\mq\rabbitmq-tutorials-master\rabbitmq-tutorials-master\demo\target\classes started by 86130 in D:\prj\mq\rabbitmq-tutorials-master\rabbitmq-tutorials-master\demo)
2020-06-16 15:16:58.673  INFO 2348 --- [           main] com.example.demo.DemoApplication         : The following profiles are active: test1,receiver
hello
2020-06-16 15:16:59.209  INFO 2348 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 0.811 seconds (JVM running for 1.447)
Ready ... running for 10000ms

Process finished with exit code 0
--------------------------------------------
It seems my project started as a usual SpringBoot Project,and is diffierent from the tutorial project.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I'm afraid we cannot suggest much since you haven't provided any examples of what you did (e.g. how the CLI runner was invoked, from what directory) or server logs. Consider putting together an example GitHub repository, a PowerShell transcript to demonstrate how you run it, collecting logs, and starting a mailing list thread. Guessing is a very time-consuming way to debug things so we try to avoid it in this community.
