### ISSUE TITLE
exists unacked message

### ISSUE THREAD

**Issue by zhangj311** [rabbitmq/discussions#118]
hi, the queue has ten consumers running and cann't find message info in consumers' logs, but the queue always has unacked messages.

**Comment by michaelklishin** [comment]
We cannot suggest much with the amount of information provided. Very likely your applications do not acknowledge those deliveries and have run into a [prefetch limit](https://www.rabbitmq.com/confirms.html#channel-qos-prefetch). You can restart the applications or force close their connections via `rabbitmqctl` or management UI and they will get redeliveries.

Unhandled exceptions in consumers is one common reason for messages not being unacknowledged. This depends on the client library used and what your code does. See your application's logs, metrics and error handling around delivery handlers.
Only you know what your applications do and ways in which they can fail to acknowledge deliveries. Any [channel exceptions](https://www.rabbitmq.com/channels.html#error-handling) would result in delivery requeueing, so that can be ruled out as a possible issue.

[Consumer Acknowledgements guide](https://www.rabbitmq.com/confirms.html) covers more or less everything there is about manual acknowledgement mode.
