### ISSUE TITLE
Compatibility with since rabbitmq 3.8.4

### ISSUE THREAD

**Issue by exeos** [rabbitmq/discussions#129]
Hello,
Since rabbitmq 3.8.4 i have logs duplicate error each n second that appear even if the plugins is working.

Problem reading some plugins: [
{"/usr/lib/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.8.0.ez", duplicate_plugin}
]

Do you have same issue ?
It's perfectly working with rabbitmq 3.8.3

**Comment by exeos** [comment]
I'm using the latest available version :
https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/tag/v3.8.0 for 3.8.3 or 3.8.4
And the issue still here in 3.8.5

**Comment by michaelklishin** [comment]
@exeos the issue is that you have two versions (`.ez` files) of this plugin on code path. The node warns about it as quite often this can lead to highly unpredictable behavior when modules from two different versions can be mixed on the node. You need to remove one of the versions (files) in the plugins directory which can be discovered using

```
rabbitmq-plugins directories
```

against a running node.

**Comment by michaelklishin** [comment]
If there is only one plugin then there may be a stale directory left in the [expanded plugins directory](https://www.rabbitmq.com/plugins.html#plugin-directories) (which `rabbitmq-plugins directories` would also mention).

Stop the node, remove the entire expanded plugins directory and start the node back. It will expand only the plugins already in place.

**Comment by exeos** [comment]
Fixed:
It seems that if i move the plugin from /usr/lib/rabbitmq/plugins/ to
/usr/lib/rabbitmq/lib/rabbitmq_server3.8.5/plugins/ it's working.
This is needed since 3.8.4 to not have the duplicate log message.

thanks a lot

Le ven. 3 juil. 2020 à 17:52, Michael Klishin <notifications@github.com> a
écrit :
