### ISSUE TITLE
Prometheus plugin not show queues on metrics on 3.8.5

### ISSUE THREAD

**Issue by aalemanq** [rabbitmq/discussions#134]
Hello, I try to find some info about this but I don't find it, sorry if this topic is exist.

I don't know why, but If I upgrade my rabbitmq from 3.8.2 management to 3.8.5 , my metrics not show my queues, and my grafana dashboard is not show anyway this queues like in the past. Do you know if I'm wrong with something?

With 3.8.2
![image](https://user-images.githubusercontent.com/37634573/88932512-7b072700-d27e-11ea-98d3-a3db13ca874c.png)

With 3.8.5
![image](https://user-images.githubusercontent.com/37634573/88932521-7fcbdb00-d27e-11ea-83ba-a7bf4b30fa47.png)

So, queue names are not showed from prometheus!!!

3.8.2
![image](https://user-images.githubusercontent.com/37634573/88932863-ee109d80-d27e-11ea-9531-5010b62f6e68.png)

3.8.5
![image](https://user-images.githubusercontent.com/37634573/88932560-89554300-d27e-11ea-963c-d3611db37723.png)

Can see the diference¿?¿? I don't know if something was changed in new versions?

**Comment by michaelklishin** [comment]
Besides the obvious step of making sure that the plugin is actually enabled after whatever upgrade procedure is performed,
you can query the scraping endpoint using `curl` or similar and what it returns. Modern versions have [metric aggregation enabled by default](https://www.rabbitmq.com/prometheus.html#metric-aggregation) so if you assume per-object metrics, you have to opt-in as explained in the docs.

See https://github.com/rabbitmq/rabbitmq-prometheus/issues/24 for the background. https://github.com/rabbitmq/rabbitmq-prometheus/issues/26 introduced the aggregation and shipped in `3.8.3`.

**Comment by aalemanq** [comment]
Thanks a lot for your response, it helps me a lot.

For another hand, every thing is right about your post and my new rabbit can show queues. But, do you know how can I setup this config with enviroments via docker? I tried so much things like:

-Enviroment like this in compose:

`      RABBITMQ_CTL_ERL_ARGS: -rabbitmq_prometheus return_per_object_metrics true
`

or

`      RABBITMQ_CTL_ERL_ARGS: -prometheus return_per_object_metrics true
`

Or advanced.config file with:

`[
  {rabbit, [{prometheus, [{return_per_object_metrics,           "true"}]}]}
].

`

nothing works. I deploy my rabbit with enviroments and secrets in docker swarm and I want to avoid dockerfile and static fileconfig (with rabbitmq.conf static file is works like a charm)

Regards!

**Comment by michaelklishin** [comment]
@aalemanq we strongly recommend configuring such basic settings in the config file. Erlang's application environment flags is something we have used in one of our products and it turned out to be a pretty bad idea.

I'm not sure where does the

```
{rabbit, [{prometheus, [{return_per_object_metrics, "true"}]}]}
```

example come from or what leads you to believe that `RABBITMQ_CTL_ERL_ARGS` is used by the server (that's not the case, only CLI tools use it).

The advanced config key is `rabbitmq_prometheus.return_per_object_metrics`, so

``` erl
[
  {rabbitmq_prometheus, [
    {return_per_object_metrics, true}
  ]}
].
```

You can see it [in the plugin's configuration schema file](https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/priv/schema/rabbitmq_prometheus.schema#L15).

The Prometheus plugin does not use any environment variables but anything passed via runtime arguments would equally apply to it. However, our team strongly discourages the heavy use of environment variables where a config file entry would do. The benefits
of using a config file are numerous, including configuration key and value validation and the discoverability of your settings.

**Comment by aalemanq** [comment]
Thanks for your response, I find a solution and is putting advanced.config file in /etc/rabbitmq with next content:

`[
  {rabbitmq_prometheus,[{return_per_object_metrics,true}]}
].
`

Thanks a lot!
