### ISSUE TITLE
metrics for nodes in a cluster

### ISSUE THREAD

**Issue by haarchri** [rabbitmq/discussions#144]
today we had the problem that 2 rabbitmq nodes are available but not in the cluster - but we see both with metrics in prometheus 

is it possible to get the metrics via rabbitmq-prometheus to monitor if a cluster member is not part of a cluster anymore ? we didn't find a metric like this - possible is the amount of members because we didn't use autoscaling 

insights:
situation:
![image](https://user-images.githubusercontent.com/21083497/93593011-8be93480-f9b3-11ea-8289-5f7d97699d4e.png)

expected:
![image](https://user-images.githubusercontent.com/21083497/93592981-7f64dc00-f9b3-11ea-8440-af942b76a228.png)

**Comment by michaelklishin** [comment]
To express if a node is "in a cluster", you can either set a threshold on the number of nodes online — something that should already be possible with the Grafana dashboards provided — or monitor a set of cluster IDs reported by all monitored nodes and expect it to be identical. This is not a great idea because `cluster_name` can be set by the operator to any value.

There is an internally used cluster ID and schema database cookie (no relation to the Erlang cookie) which are both unique per cluster in practical terms but are not meant to be publicly exposed.

You haven't specified *why* these nodes were "available but not in a cluster". A node that cannot join a cluster due to an internal ID mismatch will log it, and so will the peer it tried to join. Such events could be a metric of its own. Or it could be a [well known natural race condition during initial cluster formation](https://www.rabbitmq.com/cluster-formation.html#initial-formation-race-condition): in this case, without exposing internal cluster ID, the total number of nodes reported by each peer is the only way to detect this that's reasonably easy to implement and explain.

This is open source software, so instead of asking others to come up with a solution, you are welcome to come up with a metric, pitch it to the community or the core team, and contribute it.

**Comment by michaelklishin** [comment]
@gerhard
