### ISSUE TITLE
Performance related question

### ISSUE THREAD

**Issue by revoorunischal** [rabbitmq/discussions#153]
Hi ,
   I tried to implement rabbitmq-mqtt plugin for my IOT usecase. I found this to be very easy to implement it server side especially using spring-cloud-stream rabbitmq plugin.

But I am worried about the rabbitmq architecture of one queue per consumer if the message needs to be sent uniquely to it.
If I take a real world scenario where I have 1 million devices, then this will actually create 1 million connections 1 million channels and and 1 million queues with unique routing key. Will the server handle so many ?

How many clusters will be required and by increasing the cluster wont It reduce my TPS ?

I observed one thing is as I increase the number queues with same routing key the TPS of my application goes down. I am using RabbitMQ 3.8.8, Erlang 23.0.3 my exchange was a topic exchange where routing key was my topic.

**Comment by michaelklishin** [comment]
Binding N queues with the same routing key to a topic means each queue gets a copy. This obviously will have close to linear operation per second decline, with any number of cluster nodes. MQTT in general, regardless of the implementation, is not a great fit for such mass fanouts. Non-destructive consumers of a shared stream of messages, something that is coming in RabbitMQ 3.9, is a much better fit since every message is then stored just once and not 1M times. This is not really something that MQTT v3.1 makes easy to expose, so you will have to use a different protocol and client in all likelihood. This is not really RabbitMQ-specific.

[Tuning for a Large Number of Connections](https://www.rabbitmq.com/networking.html#tuning-for-large-number-of-connections) explains what the important resource usage factors are. Adding more cluster nodes means you can handle more connections assuming a reasonably even distribution of them between nodes. It largely goes the same for client-specific queues that are not [mirrored](https://www.rabbitmq.com/quorum-queues.html). Mirroring to a quorum of nodes will greatly reduce the benefit of every additional node.
