### ISSUE TITLE
RabbitMQ Connection Holds For One Day

### ISSUE THREAD

**Issue by esraince1** [rabbitmq/discussions#158]
In our production environemt we have rabbitmq cluster with 3 nodes. Our client version is 4.1.3.We publish event in current transaction completed event. But for more than 10 hours our transaction completed event never ends. At that time there was a network partition in our rabbitmq cluster and we restarted server. In our rabbitmq client heartbeat value is 0 and we open a new channel for each enqueue. Can rabbitmq operation cause that much long operation time like more than 10 hours ?

**Comment by michaelklishin** [comment]
I'm not sure what "holds" means. RabbitMQ has no limit on how long a connection or channel can stay open. There can be other reasons, from genuine network disruptions to [client errors](https://www.rabbitmq.com/channels.html#error-handling) to [proxies or load balancers](https://www.rabbitmq.com/networking.html#intermediaries) that may have a connection inactivity timeout (it usually is a lot lower than one day by default).

Only logs and metrics can tell. We do not guess in this community. All connection lifecycle operations [are logged](https://www.rabbitmq.com/logging.html#logged-events).

We highly recommend *not* disabling heartbeats; it's a truly terrible idea that masks the problem of connection loss and does not actually solve anything. Channels are [meant to be long lived](https://www.rabbitmq.com/channels.html).

Also, see if there are any alarms in the logs since they block all publishing connections. Using a separate connection for publishing and another one for consuming — both long lived — is a safer option that means even if the publishing one is blocked, consumer acknowledgments will still be processed.

**Comment by michaelklishin** [comment]
Oh, and opening a new channel for every publish operation is *not* how channels are supposed to be used, not recommended, and very frequently leads to [channel leaks](https://www.rabbitmq.com/channels.html#monitoring) which then exhausts the `channel_max` limit (no, please *DO NOT* disable it as you did with heartbeats), which is an unrecoverable connection error in the protocol. Node logs and metrics will be able to confirm or deny this hypothesis.
