### ISSUE TITLE
dynamic join/forget rabbitmq node：connection.start was never received, likely due to a network timeout

### ISSUE THREAD

**Issue by raochunjiang** [rabbitmq/discussions#24]
hei guys，this problem just happen when i use **haproxy** to transmit your client's tcp connections. following is part of my `haproxy.cfg`:

```sh
listen rabbitmq_cluster
    bind *:5672
    mode tcp
    balance roundrobin
    server k8s-cluster-5672 192.168.199.17:5672 check inter 2000 rise 2 fall 3 weight 1
    server docker01 192.168.199.16:35672 check inter 2000 rise 2 fall 3 weight 1
    server ryan-5672 192.168.198.173:5672 check inter 2000 rise 2 fall 3 weight 1
```

when i try to add a server node in the cluster, or remove one, my client throws an exception:

``` cs
connection.start was never received, likely due to a network timeout
```

acturally i find some code in you source:

![image](https://user-images.githubusercontent.com/27672276/70120890-7f0b8680-16a8-11ea-814c-8e7560da46a6.png)

and it doesn't wait anymore, and give me `null` immediately.

can you help me to find out why?  my feeling is perhaps i can do some modifications to my `haproxy.cfg` to resolve this problem.

thank you!

**Comment by michaelklishin** [comment]
If a connection does not receive a `connection.start` frame in a window of time, it assumes that it cannot proceed.

We cannot know for sure why this happens. Maybe the connection was initiated to the node that you are removing. Maybe HAproxy's checks are too aggressive and client's connection is closed to early. The .NET client connects to HAproxy and won't be aware of any upstream changes by definition.
It also won't retry initial connections ([connection recovery](https://www.rabbitmq.com/amqp-wireshark.html) is a different story) but your own code can.

A newly added node will NOT be immediately available to serve client connections, so if you update HAproxy upstream set too early, then HAproxy will try to connect nowhere. `rabbitmq-diagnostics check_port_connectivity` can be used as a readiness probe.

See HAproxy logs and a [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html). [Troubleshooting Networking](https://www.rabbitmq.com/troubleshooting-networking.html) could help although the culprit is in the upstream node termination failure.

**Comment by michaelklishin** [comment]
What has to change is how your client handles connection failures. It has to be able to retry them.

Unfortunately HAproxy only can perform most basic [health checks](https://www.rabbitmq.com/monitoring.html#health-checks) that won't tell you much and the readiness criteria is also extremely basic. Checking every 2 seconds is aggressive, see [Monitoring Frequency](https://www.rabbitmq.com/monitoring.html#monitoring-frequency). 10-15 seconds makes more sense for a proxy. Of course, the fundamental problem is that a client can connect
exactly at the time of upstream set changes, and HAproxy won't be able to successfully connect upstream, so it will close the client's connection or time out on it. That's perfectly fine. Your applications needs to be ready to retry N times every, say, 5 seconds.
