### ISSUE TITLE
Issue reaching port 15670

### ISSUE THREAD

**Issue by tryhardest** [rabbitmq/discussions#49]
Having trouble reaching the port example on Rancher in combination with RMQ HA.

Has anyone done this.

**Comment by lukebakken** [comment]
Please provide more information:

* What is "Rancher"?
* How exactly are you using this project? What commands are you running, what is their output, etc?
* "trouble reaching the port example" - does this mean you can't connect to port `15670`? How are you trying to connect?

**Comment by tryhardest** [comment]
Hi @lukebakken why closed without time for me to answer? Sorry but that seems unusual. Fine to ask for more info I am happy to give to best of my abilities.

Rancher is a cross platform cloud GUI we use to manage K8s. Regardless, let's put that aside maybe it confuses it. 

We tried via Rancher GUI using the RabbitMQ HA Helm chart to connect to 15670. To no avail. Maybe this is a Rancher issues, so we are also exploring that avenue, but, I'm curious how would one open the port normally?

**Comment by lukebakken** [comment]
> Hi @lukebakken why closed without time for me to answer? Sorry but that seems unusual. Fine to ask for more info I am happy to give to best of my abilities.

Because the RabbitMQ team doesn't use GitHub issues for discussions, and there was no information provided by you with which to try and help, and most people don't follow up anyway with the information we request.

In your case, I have no logs to work with, and no means to reproduce your issue. Any guidance I give would be a guess.

If you need assistance with kubernetes, I suggest asking in k8s-specific forums. You may also be able to find information by searching the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list archives. People frequently ask k8s related questions there and we try to help out.

Finally, our documentation could be useful:

* https://www.rabbitmq.com/cluster-formation.html#peer-discovery-k8s
* https://www.rabbitmq.com/troubleshooting-networking.html
