### ISSUE TITLE
Problem in rabbit with normal and less traffic

### ISSUE THREAD

**Issue by kaaaq** [rabbitmq/discussions#69]
Hi,
Im using rabbitmq cluster (v3.7.15) in production but i have problem with it, it can not resist with even normal traffic and it crashes with only 1200 req/second !!!, and i have this error messages on my servers:
`Uncaught PhpAmqpLib\\Exception\\AMQPTimeoutException: The connection timed out after 3 sec while awaiting incoming data.`

And network error but nodes can ping each other.
what should i do for solving this problem?
Best regards.

**Comment by michaelklishin** [comment]
You have provided no evidence that RabbitMQ "crashes".

The exception suggests that your client fails to connect and reasons for that can [vary greatly](https://www.rabbitmq.com/troubleshooting-networking.html), including the node and your PHP application [running out of file descriptors](https://www.rabbitmq.com/networking.html#open-file-handle-limit). `ping` only can tell you so much (and it doesn't even use TCP), as the Troubleshooting Networking guide explains.

Since the PHP client cannot use [long lived connections](https://www.rabbitmq.com/connections.html#lifecycle), it almost certainly produces [high connection churn](https://www.rabbitmq.com/connections.html#monitoring) with such message rate. There's a [proxy from CloudAMQP](https://github.com/cloudamqp/amqproxy) that at least partially addresses this problem.

When in doubt, consult log files and [take a traffic capture](https://github.com/cloudamqp/amqproxy).

**Comment by kaaaq** [comment]
I correct my question, it doesnt crash but it shows this error and we can not connect to it!:
`Uncaught PhpAmqpLib\\Exception\\AMQPTimeoutException: The connection timed out after 3 sec while awaiting incoming data`
And there is no any limitation on file descriptors, it set on 1M.

**Comment by kaaaq** [comment]
And we dont have any problem with Long Lived Connection in PHP and i checked chrun statistics diagram, we dont have problem on it too.but still we get this error :
`Uncaught PhpAmqpLib\\Exception\\AMQPTimeoutException: The connection timed out after 3 sec while awaiting incoming data`

**Comment by michaelklishin** [comment]
[Target node logs](https://www.rabbitmq.com/logging.html#logged-events) and a traffic capture would provide relevant information. We cannot suggest anything with a single line error message.

A three second timeout sounds overly aggressive. This is explained [in the Heartbeats guide]https://www.rabbitmq.com/heartbeats.html).

**Comment by kaaaq** [comment]
How can i see logs?
there is no log after disconnecting nodes in journalctl and /var/log/[nodename].log

**Comment by kaaaq** [comment]
And my heartbeats time is not 3 seconds
and it isnt related to heartbeat because it cant make a connection to rabbitmq
I think your missunerstood is because of incorrect php logs, it is php log, NOT Rabbit log....
and i checked /var/log/rabbitmq.conf , there wasn't any good error to relate this problem...

**Comment by kaaaq** [comment]
This is complete error text:
`"Uncaught PhpAmqpLib\\Exception\\AMQPTimeoutException: The connection timed out after 3 sec while awaiting incoming data in /var/www/html/eitaa/Lib/composer/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:141\nStack trace:\n#0 /var/www/html/eitaa/Lib/composer/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(163): PhpAmqpLib\\Wire\\AMQPReader->wait()\n#1 /var/www/html/eitaa/Lib/composer/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\\Wire\\AMQPReader->rawread(7)\n#2 /var/www/html/eitaa/Lib/composer/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(566): PhpAmqpLib\\Wire\\AMQPReader->read(7)\n#3 /var/www/html/eitaa/Lib/composer/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(623): PhpAmqpLib\\Connection\\AbstractConnection->wait_frame(3)\n#4 /var/www/html/eitaa/Lib/composer/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(234): PhpAmqpLib\\Connection\\AbstractConnection->wait_channel(0, 3)\n#5 /var/",
"/var/www/html/eitaa/Lib/composer/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php",`

**Comment by kaaaq** [comment]
this is my PHP erorr, and no connection created in rabbitmq

**Comment by michaelklishin** [comment]
I did not say that your heartbeat timeout is set to 3 seconds. The error message says that "a connection timed out after 3 seconds" which could mean TCP connection, I don't maintain the PHP client so not really sure.

Log file locations [are documented](https://www.rabbitmq.com/relocate.html). In most recent RabbitMQ versions there is also `rabbitmqctl log_tail -N [lines]` and `rabbitmqctl log_tail_stream` (the latter requires a running node).

A [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) would immediately reveal a lot of relevant information. [Troubleshooting Networking](https://www.rabbitmq.com/troubleshooting-networking.html) outlines a methodology that saves everyone a lot of time when troubleshooting connectivity.

**Comment by lukebakken** [comment]
You can increase the read timeout in the PHP client via the `read_write_timeout` parameter.

**Comment by kaaaq** [comment]
3 seconds is really big number for any environments!!!

**Comment by lukebakken** [comment]
You need to help us help you. Single stack traces and short descriptions of your issue is not sufficient.

* We don't have any information about what kind of hardware or virtual machines you're using.
* We have no idea if this is a new problem, or something that has recently started.
* We don't know what "network error" you're talking about in your original description.
* We don't know if you're using a load balancer or other network devices between your PHP apps and RabbitMQ.
* We don't know how many queues you're using or if they are mirrored (HA).

You have posted [several different questions on the `rabbitmq-users` list](https://groups.google.com/forum/#!searchin/rabbitmq-users/Kaaa$20K%7Csort:date). We don't know where to follow-up.

Please, provide more information. Let's continue using **ONLY** this discussion:

https://groups.google.com/forum/#!topic/rabbitmq-users/EiszUtQ5lns
