### ISSUE TITLE
Management Database Grows in Size In Seconds

### ISSUE THREAD

**Issue by gsogol** [rabbitmq/discussions#71]
Running a cluster of 3 nodes. All clients/browsers are communicating via a stomp plugin. All queues are set to autodelete. In the overview tab, you can see around 2000 connections and queues. The main issue is that the management database grows to GBs and slows the whole cluster down to the point that we can't even browse the management UI (super slow) and connections are erring out.

Here is what we see:
Overview tab --> https://drive.google.com/file/d/1VzzqE4u90vxvt3ygIgrBn0JJndK8m2Es/view?usp=sharing

Memory usage --> https://drive.google.com/file/d/1bqeRggCGk-zVQbMjhpbpKjkTDHuZHMaW/view?usp=sharing

`rabbitmqctl eval 'rabbit_mgmt_storage:reset_all().'` --> does not reset the management db.

`rabbitmqctl eval 'supervisor2:terminate_child(rabbit_mgmt_sup_sup, rabbit_mgmt_sup), rabbit_mgmt_sup_sup:start_child().'` --> does reset the management database but it quickly goes back to 3-10 GB

rabbitmq.config (no policies are configured at all) --> 
`
[
{rabbit,
  [
    {loopback_users, []}
  ]},
{rabbitmq_management,
  [
    {rates_mode, none}
  ]}
]`

RabbitMQ version: 3.7.18
Erlang version 22.1
RabbitMQ plugin information via `rabbitmq-plugins list` -->
```
[  ] rabbitmq_amqp1_0                  3.7.18
[  ] rabbitmq_auth_backend_cache       3.7.18
[  ] rabbitmq_auth_backend_http        3.7.18
[  ] rabbitmq_auth_backend_ldap        3.7.18
[  ] rabbitmq_auth_mechanism_ssl       3.7.18
[  ] rabbitmq_consistent_hash_exchange 3.7.18
[  ] rabbitmq_event_exchange           3.7.18
[  ] rabbitmq_federation               3.7.18
[  ] rabbitmq_federation_management    3.7.18
[  ] rabbitmq_jms_topic_exchange       3.7.18
[E*] rabbitmq_management               3.7.18
[e*] rabbitmq_management_agent         3.7.18
[  ] rabbitmq_mqtt                     3.7.18
[  ] rabbitmq_peer_discovery_aws       3.7.18
[  ] rabbitmq_peer_discovery_common    3.7.18
[  ] rabbitmq_peer_discovery_consul    3.7.18
[  ] rabbitmq_peer_discovery_etcd      3.7.18
[  ] rabbitmq_peer_discovery_k8s       3.7.18
[  ] rabbitmq_random_exchange          3.7.18
[  ] rabbitmq_recent_history_exchange  3.7.18
[  ] rabbitmq_sharding                 3.7.18
[  ] rabbitmq_shovel                   3.7.18
[  ] rabbitmq_shovel_management        3.7.18
[E*] rabbitmq_stomp                    3.7.18
[  ] rabbitmq_top                      3.7.18
[E*] rabbitmq_tracing                  3.7.18
[  ] rabbitmq_trust_store              3.7.18
[e*] rabbitmq_web_dispatch             3.7.18
[  ] rabbitmq_web_mqtt                 3.7.18
[  ] rabbitmq_web_mqtt_examples        3.7.18
[E*] rabbitmq_web_stomp                3.7.18
[  ] rabbitmq_web_stomp_examples       3.7.18`
```

Running the `rabbitmq-collect-env`--> https://drive.google.com/file/d/1QgYNaVxwmt52OmwOF9OBwNqub8KBVcRQ/view?usp=sharing

We stood up another 3 node cluster with similar as above running load tests but could not recreate the management db issue like the cluster above running in prod. What can we do to figure out what is happening?

**Comment by michaelklishin** [comment]
While we cannot make any conclusions from just one `rabbitmqctl maybe_stuck` run, there are two processes that are stuck in calls into `rabbit_mgmt_db :submit_cached/4`. That delegates to `rabbit_mgmt_db_cache:fetch/4` which depends on a few processes that cache inter-node requests.
So those pending operations are likely be accumulating.

**Comment by michaelklishin** [comment]
The easiest option to "reset" this plugin is to disable and then re-enable it on all nodes.

**Comment by michaelklishin** [comment]
It should be mentioned that exactly this sort of effects from the monitoring plugin on the system being monitored is what is [documented](https://www.rabbitmq.com/monitoring.html#external-monitoring) and greatly reduced if not eliminated in the [Prometheus plugin](https://www.rabbitmq.com/prometheus.html). Inter-node request caching does not exist there, for example, because every node only serves its own stats.

**Comment by gerhard** [comment]
Based on the memory breakdown that you have shared, I can see that the majority is in ETS (management DB) as well as heap (plugins). Can you share screenshots of the following please:

- `rabbitmq-diagnostics observer` - lists processes by memory usage
- Press `E <ENTER` - lists ETS tables by memory usage

This is what I expect to see for your node:

![image](https://user-images.githubusercontent.com/3342/76202061-28a06d80-61ec-11ea-8ab5-bb66ba3a1810.png)
![image](https://user-images.githubusercontent.com/3342/76202074-2e964e80-61ec-11ea-86b9-68a9b65f3ea4.png)

[Disabling metrics in Management UI should help with slow UI](https://github.com/rabbitmq/rabbitmq-management-agent/pull/78). You will need to upgrade to v3.8.2.

You may find these useful:

- [How to upgrade from RabbitMQ 3.7 to 3.8?](https://github.com/rabbitmq/tgir/tree/master/s01/e01)
- [Help! RabbitMQ ate my RAM!](https://github.com/rabbitmq/tgir/tree/master/s01/e02)

**Comment by gsogol** [comment]
@gerhard per your request,
https://drive.google.com/file/d/10e0vZquyiPQpA04RLxi-SjFxuBcNtNeX/view?usp=sharing
https://drive.google.com/file/d/1ov54-4BwQHK5C8N3M1zSjBzY58iBYFXi/view?usp=sharing

**Comment by gsogol** [comment]
Here are more for node 2 where management database is at 13GB

![rabbit-diag-obs-node-2-2](https://user-images.githubusercontent.com/2625918/76248005-daed2a80-6216-11ea-8562-081d7decd204.PNG)
![rabbit-diag-obs-node-2-1](https://user-images.githubusercontent.com/2625918/76248010-dd4f8480-6216-11ea-854b-d058ddb03eba.PNG)

**Comment by gerhard** [comment]
Your latest screenshots show that there is no shared data structure (a.k.a. ETS) which accounts for memory usage, meaning that there is no management database growth. As a result running `rabbit_mgmt_storage:reset_all().` does nothing to memory usage, as you've already observed.

The bulk of memory is used by the `rabbit_mgmt_db_cache_queues` process. I am assuming this has to do with the high queue churn rate, where metrics for queues that no longer exist are kept in this cache longer than they should. To verify that this is true, run the following command: `rabbitmqctl eval 'kill(whereis(rabbit_mgmt_db_cache_queues), force_reset).'` and observe the memory usage drop. As soon as anything requests `GET /api/queues`, the newly spawned `rabbit_mgmt_db_cache_queues` process will start using memory again. In my local testing, I have observed that for 10,000 queues `rabbit_mgmt_db_cache_queues` uses 65MB. I cannot imagine how many transient queues your node must have had for this process to use 10GB, as captured in your last observer-cli screenshot. @dcorbacho or @kjnilsson may have more context/details.

The simplest thing that I would recommend is to disable metrics monitoring for queues. This will prevent metrics filling `rabbit_mgmt_db_cache_queues`. If the RabbitMQ monitoring that you are using hits `GET /api/queues`, which I suspect is what happens in your case, it will result in a lot of memory bloat in this process. FWIW, the Management UI limits the queues returned to 100. I am observing 1.7MB memory usage in this case.

Next, I would recommend that you upgrade to v3.8.3 and [disable statistics & metrics in RabbitMQ Management](https://www.rabbitmq.com/management.html#disable-stats). I can confirm that with stats disabled, this is what I am observing:

<img width="987" alt="Screenshot 2020-03-10 at 11 21 09" src="https://user-images.githubusercontent.com/3342/76308031-dfbae880-62c1-11ea-87ac-2b06ed9c0528.png">

Without stats disabled:

<img width="986" alt="Screenshot 2020-03-10 at 11 23 11" src="https://user-images.githubusercontent.com/3342/76308133-0c6f0000-62c2-11ea-9901-3ba289a03db3.png">

To go further, you can also disable agent metrics collection via `management_agent.disable_metrics_collector`. This is what you can expect:

<img width="979" alt="Screenshot 2020-03-10 at 11 40 50" src="https://user-images.githubusercontent.com/3342/76309660-1e9e6d80-62c5-11ea-8eb9-ccdd2ba33db1.png">

For metrics/monitoring, read our [Monitoring with Prometheus & Grafana guide](https://www.rabbitmq.com/prometheus.html), including info on the [Grafana dashboards that we maintain](https://grafana.com/orgs/rabbitmq). If you want more background on the broader topic of RabbitMQ monitoring/observability, watch these:

- [Observe and understand RabbitMQ - RabbitMQ Summit 2019](https://www.youtube.com/watch?v=L-tYXpirbpA)
- [The New Metrics System in RabbitMQ 3.8](https://github.com/rabbitmq/tgir/tree/master/s01/e00)

Let us know how it goes.

**Comment by gsogol** [comment]
This is what I get when running the command...

![image](https://user-images.githubusercontent.com/2625918/76344754-7befea00-62d8-11ea-84f7-6b7f37b7478a.png)

**Comment by gerhard** [comment]
A queue will need to be defined & a request to `GET /api/queues` will need to have been made on that node for the `rabbit_mgmt_db_cache_queues` process to be created. Also, the function is `exit`, not `kill`:

```
rabbitmqctl eval 'exit(whereis(rabbit_mgmt_db_cache_queues), force_reset).'
```

**Comment by gsogol** [comment]
@gerhard  running the command made the management db go from 12GB to 1.7GB. 

When disabling the metrics, what info would be lost? And is that the recommended solution now?

**Comment by gerhard** [comment]
> When disabling the metrics, what info would be lost?

No metrics will show in Management, meaning that Management will look pretty empty, and some tabs will not load anything because there is nothing to show. This also means that it will be fast and efficient.

All metrics that exist in Management are exposed as Prometheus metrics from 3.8.0 onwards. Our long-term goal is to remove all metrics from Management and keep this just for - wait for it -management tasks only 💡 

> And is that the recommended solution now?

If a RabbitMQ node has a significant amount of metrics that take away CPU and/or memory from processing message then disabling stats is the recommended solution, yes.

@kjnilsson is working on https://github.com/rabbitmq/rabbitmq-management/pull/788 that may help your specific use-case, but long-term you are much better off removing almost all pressure on resources that metrics (stats) currently have and delegating this task to systems that were built for it, such as Prometheus & Grafana. For what it's worth, enabling rabbitmq-prometheus plugin allows you to integrate with any metrics SaaS that supports the Prometheus exposition format. [Datadog Agent for example supports this since 2018](https://www.datadoghq.com/blog/monitor-prometheus-metrics/), [as does InfluxDB](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus). I'm sure other SaaS support this as well, [it's something worth exploring](https://www.rabbitmq.com/monitoring.html#monitoring-tools).

> Should we may be change the interval instead? Thoughts?

In my local tests, changing the stats sampling interval didn't result in any improvement for your specific use-case. If you don't want to change anything, then https://github.com/rabbitmq/rabbitmq-management/pull/788 is most likely to help you.

**Comment by gsogol** [comment]
Thank you so much for the wealth of knowledge @gerhard. I have what I need and hope it helps others. 

My last question is where to set the `management_agent.disable_metrics_collector = false`

We are currently using rabbitmq.config (old format). Dies it go in there or some other config file?

**Comment by michaelklishin** [comment]
Configuration files are [pretty decently documented](https://www.rabbitmq.com/configure.html#configuration-files) since the early 3.7.x releases, which is over two years now.

No, 

``` erlang
[
  {rabbit, [
    {loopback_users, []}]},
    {rabbitmq_management, [
      {rates_mode, none}, 
     {management_agent.disable_metrics_collector, false}]
  }
].
```

certainly does not look correct because `management_agent.disable_metrics_collector` is a new style config file setting and must go into `rabbitmq.conf`. It's classic config style equivalent is [`rabbitmq_management_agent.disable_metrics_collector`](https://github.com/rabbitmq/rabbitmq-management-agent/blob/master/priv/schema/rabbitmq_management_agent.schema#L3):

``` erlang
[
  {rabbit, [
    {loopback_users, []}]},
    {rabbitmq_management, [
      {rates_mode, none}]
  },
  {management_agent, [
     {disable_metrics_collector, false}
  ]}
].
```

This config file can be moved to `advanced.config` (see the docs) and specific settings can be moved to `rabbitmq.conf`.

While at it, enabling remote `guest` user connections is a [poor practice](https://www.rabbitmq.com/production-checklist.html#users) and  `rabbitmq_management.rates_mode`'s new style config equivalent is

``` ini
management.rates_mode = none
```

**Comment by gsogol** [comment]
Thanks y'all.
