### ISSUE TITLE
How subscribe to queue with arguments in headers exchange?

### ISSUE THREAD

**Issue by lampaa** [rabbitmq/discussions#73]
With Java  (AMQP):
1) I create exchange, queues and arguments of bindings.
![image](https://user-images.githubusercontent.com/927585/76305404-24e91580-62d6-11ea-9632-da04d4e9dab9.png)
2) Next, i subscribe with need filter (example: code: 100), its all works.

With STOMP (over websockets):
How subscribe to queue with arguments?
I tried put to headers params: x-match: all, code: 100, but it not works, arguments are not created:

```
SUBSCRIBE
auto-delete:true
durable:true
exclusive:false
x-queue-name:browser.entity_Location.unique(0.3570864444965518)
code:100
x-match:all
id:sub-0
destination:/exchange/Test/browser.entity_Location
```

![image](https://user-images.githubusercontent.com/927585/76306303-b442f880-62d7-11ea-8bab-6dc60345a08d.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
You have to bind a queue to this exchange using a set of arguments that makes sense. Distribution of messages happens between queues at [routing time](https://www.rabbitmq.com/tutorials/amqp-concepts.html), not consumer registration (subscription) time. This cannot be done over STOMP and it's not clear whether we will accept https://github.com/rabbitmq/rabbitmq-stomp/pull/144 which tries to make that possible.

STOMP is entirely unaware of exchanges. There are no exchanges in STOMP. You can set up the topology using an AMQP 0-9-1 client and then consume using STOMP.
